@url = http://54.159.32.73:4000/api/v1.0/user_panel/auditors
@local_url = http://192.168.32.116:4000/api/v1.0/user_panel/auditors
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJyYWh1bHRyaXZlZGkxODBAZ21haWwuY29tIiwidXNlcm5hbWUiOiJyYWh1bHRyaXZlZGkxODAiLCJpYXQiOjE2MDAxNjI0OTAsImV4cCI6MTYwMDI0ODg5MH0.PlsNNgItiv1XvITchg2Ng3jEsxswIsD6gag4zpzEA3A

### Get all auditors
GET {{local_url}} HTTP/1.1
Authorization: {{token}}

### Get auditor
GET {{local_url}}/2 HTTP/1.1
Authorization: {{token}}

### Get auditors by specific assessment id
GET {{local_url}}/assessment/1 HTTP/1.1
Authorization: {{token}}

### create auditor
POST {{local_url}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "vFirstName": "Spider",
  "vLastName": "Man",
  "vEmail": "spiderman@gmail.com",
  "vPhone": "9825420198",
  "vCompany": "Marvel",
  "iAssessmentId": 8
}

### delete auditor
DELETE {{local_url}}/2 HTTP/1.1
Authorization: {{token}}

### update auditor
PATCH {{local_url}}/3 HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "vFirstName": "Rahul",
  "vLastName": "Trivedi",
  "vEmail": "rahultrivedi180@gmail.com",
  "vPhone": "9825420198",
  "vCompany": "Old Company"
}