@local_url = http://localhost:4000/api/v1.0/user_panel/forgot_password
@live_url = http://54.159.32.73:4000/api/v1.0/user_panel/forgot_password
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJkZWFkQHBvb2wuY29tIiwidXNlcm5hbWUiOiJkZWFkIiwiaWF0IjoxNTkxNjcyNTI2LCJleHAiOjE1OTE3NTg5MjZ9.l08Iw5ICg68iMrww6b_oJ1_RRvy6FJuNq_1i9ldB1HQ

###
POST {{local_url}}/sendMail HTTP/1.1
Content-Type: application/json

{
  "email": "rahultrivedi180@gmail.com"
}

###
POST {{local_url}}/changePassword HTTP/1.1
Content-Type: application/json

{
  "email": "rahultrivedi180@gmail.com",
  "password": "123456",
  "otp": "53426"
}