@local_url = http://localhost:4000/api/v1.0/admin_panel/poa_records
@live_url = http://54.159.32.73:4000/api/v1.0/admin_panel/poa_records
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpQWRtaW5JZCI6MTM0OTEsInZFbWFpbCI6InBpbmFraW5wQGhpcnRlY2hub2xvZ3kuY29tIiwidlVzZXJOYW1lIjoicGluYWtpbnAiLCJpYXQiOjE1ODkxNjYyNTEsImV4cCI6MTU4OTI1MjY1MX0.ONDA9YtQxwB6-3LMMFB0IMZxWYt2YeOIgz9bVmZTPy4

###
GET {{local_url}} HTTP/1.1
Authorization: {{token}}

###
GET {{local_url}}/1 HTTP/1.1
Authorization: {{token}}

###
POST {{local_url}} HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "iCRId": 1,
  "POAName": "new poa",
  "POAStatus": 1,
  "ResourceStatus": 1,
  "Deficiency": "Defic"
}

###
PATCH {{local_url}}/1 HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "Deficiency": "New Defic"
}