const router = require('express').Router()

// sub routes
const adminsRoutes = require('./admins.routes')
const customerRoutes = require('./customers.routes')
const organizationsRoutes = require('./organization_mas.routes')
const rolesRoutes = require('./roles_mas.routes')
const assessmentTypeRoutes = require('./assessment_type.routes')
const checklistRoutes = require('./checklist.routes')
const assessmentRecordsRoutes = require('./assessment_records.routes')
const checklistRecordsRoutes = require('./checklist_records.routes')
const poaRecordsRoutes = require('./poa_records.routes')
const milestoneRecordsRoutes = require('./milestone_records.routes')
const dashboardRoutes = require('./dashboard.routes')
const sspFileRoutes = require('./sspFile.routes')
const evidenceRecordsRoutes = require('./evidence_records.routes')
const subscriptionPlansRoutes = require('./subscription_plans.routes')
const subTxnHistoryRoutes = require('./subscription_transactions_history.routes')
const invoiceRoutes = require('./invoice.routes')
const subscriptionCCRoutes = require('./subscription_cc.routes')
const otpRoutes = require('./otps.routes')
const passwordResetRoutes = require('./password_reset_routes')

router
  .use('/admins', adminsRoutes)
  .use('/customers', customerRoutes)
  .use('/organizations', organizationsRoutes)
  .use('/roles', rolesRoutes)
  .use('/assessment_type', assessmentTypeRoutes)
  .use('/checklist', checklistRoutes)
  .use('/assessment_records', assessmentRecordsRoutes)
  .use('/checklist_records', checklistRecordsRoutes)
  .use('/poa_records', poaRecordsRoutes)
  .use('/milestone_records', milestoneRecordsRoutes)
  .use('/dashboard', dashboardRoutes)
  .use('/sspFile', sspFileRoutes)
  .use('/evidence', evidenceRecordsRoutes)
  .use('/subscription_plans', subscriptionPlansRoutes)
  .use('/subscription_txn_history', subTxnHistoryRoutes)
  .use('/invoice', invoiceRoutes)
  .use('/subscription_cc', subscriptionCCRoutes)
  .use('/otp', otpRoutes)
  .use('/password_reset', passwordResetRoutes)

module.exports = router
